#pragma once

#include "Convert.h"
#include "DreamPad.h"
#include "FileExists.h"
#include "Ingame.h"
#include "SDL.h"
#include "minmax.h"
#include "typedefs.h"
#include <SADXModLoader.h>
#include <Windows.h>
#include <XInput.h>
#include <algorithm>
#include <cstdint>
#include <direct.h>
#include <limits>
#include <sstream>
#include <string>
#include <wtypes.h>
